### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by jooola** [directus/gatsby-source#2]
This plugin need to be fully tested in order to make the development easy. A Directus backend will be required to perform basic calls on it.

**Comment by loganwishartcraig** [comment]
Yeah, testing's a big one. 

Should we host our own Directus instance or just mock the SDK? Might be easier to mock the SDK - could be a better boundary, wouldn't want errors to occur as a result of the SDK rather than the plugin. Would also be easier to generate/maintain the mock data.

**Comment by jooola** [comment]
I had the idea of running a dumb directus instance in the CI, but you are right about mocking the SDK. Having the tests locally is better. Maybe E2E tests could be done in the future, but that's another problem.

**Comment by jooola** [comment]
Actually no, I'm not sure which way is better. Maybe testing small things by mocking the SDK is good enough for any local development, but I would definitely add some e2e testing in the CI.

**Comment by loganwishartcraig** [comment]
Honestly, e2e tests might be the way to go. So much of the plugin depends on the shape of the API responses. It would be nice to have Directus changes reflected in failed tests instead of trying to keep track of changes we'd need to make to dummy data.

I think we should implement e2e tests first, then potentially build some dummy data to test components in isolation later down the line.

Thoughts?

**Comment by jooola** [comment]
@loganwishartcraig Ok, I worked a bit on the e2e testing.

The solution I came up with is to use the CI on the Github side with docker services and to use docker-compose on the developer side.

This adds a few dependencies for testing but that's not a big deal I think.

See #8

**Comment by loganwishartcraig** [comment]
@jooola 

Sounds awesome! I'll check out that PR to see how they're set up and try contributing some test cases.

Will reach out if any questions come up!
