### ISSUE TITLE
`undefined` is added to the end of url

### ISSUE THREAD

**Issue by danielkrux** [directus/gatsby-source#23]
![image](https://user-images.githubusercontent.com/43535212/74189282-642d3380-4c50-11ea-85c7-5b9830d2d389.png)

As you can see above, `undefined` is added to the end of the link in when I try to run gatsby in develop. 

My `gatsby.config.js`

```
module.exports = {
  siteMetadata: {
    title: `Valashaan`,
    description: ``,
    author: ``,
  },
  plugins: [
    "gatsby-plugin-sass",
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
    {
      resolve: '@directus/gatsby-source-directus',
      options: {
        url: 'https://demo.directus.io',
        auth: {
          email: 'admin@example.com',
          password: 'password',
        },
      },
    }
  ],
}
```

**Comment by loganwishartcraig** [comment]
Thanks for this. Try setting the project name explicitly in the configuration. I believe the demo's project name is "thumper", so adding ```project: "thumper"``` to the config options might resolve this. I'm not sure off the top of my head if it's case sensitive, it might be "Thumper".

Might be an issue with how we're setting defaults.

**Comment by jooola** [comment]
@loganwishartcraig  Should we fail hardly when a project name is not set ? The default '_' changed to 'api', or needs a name. We should reflect that.

**Comment by loganwishartcraig** [comment]
@jooola Yeah currently we just pass ```undefined``` to the direct sdk-js if nothing was specified in the config. I don't think we ever actually explicitly set "_" as the default because per the [docs](https://docs.directus.io/guides/js-sdk.html#reference), it should default to that in the sdk itself.

The error log says the SDK "has no project" though, so I guess it's not defaulting to "_"? I think you're right though - we should probably just make the project name required in the config. Would that be considered a breaking change, or would it not matter since we're in a pre 1.0 release anyway?

As for the URL that gets logged, that's based on Directus v7 and outdated now. Think it would be better to just log the endpoint and the project name rather than the full URL, yeah?
