### ISSUE TITLE
Cannot query null values in GraphQL

### ISSUE THREAD

**Issue by ComputerCarl** [directus/gatsby-source#38]
I understand this may be a limitation of GraphQL, but I have an issue where if all the values of a field of `null`, I cannot query for the field.

Say if I have a field named `special_instructions`, and a value will rarely exist in this field, what is the recommendation? Can I tell GraphQL it's a String field somehow?

It would see rather error prone to use a filler value such as `none` which I would then have to test for in the app.

**Comment by loganwishartcraig** [comment]
Hey! This is an extension of this [issue in](https://github.com/gatsbyjs/gatsby/issues/6800) in Gatsby, which apparently already has a work around I wasn't aware of.

> Can I tell GraphQL it's a String field somehow?

Turns out, you can. See [this blog post](https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization/) for details. Assuming the exposed node name in the GraphQL schema is ```directusOrder```, you'd add the following to your ```gatsby-node.js``` config

```js

// ...

module.exports.sourceNodes = ({actions}) => {

  const { createTypes } = actions;

  // Notice the casing of the type name is proper. 
  const typeDefs = `
    type DirectusOrder implements Node {
      special_instructions: String
    }
  `;

  createTypes(typeDefs);

}

// ...

```

This will force the ```special_instructions``` field to appear on any ```directusOrder``` node just like any other ```String``` field. Note you **don't** need to write out all the fields, just the one you want to add. The other existing fields are unaffected.

You can add more fields and type adjustments as needed.

I currently would not know how to apply a solution like the above when the field is a ```relation``` type (i.e. File or M2O) rather than a simple primitive.

Short term, we should add this to the docs, long term it would be cool if we could automatically specify node types via the plugin.

Let us know if this helps.

**Comment by adiusz** [comment]
I'm running same issue with DatoCMS. I have template file for products (generating by gatsby-node), but not all products has the same fields. In result I get `TypeError: can't access property "url", data.datoCmsProduct.technicalSpec is null`. 
This is what my query looks like:

```
query WorkQuery($slug: String!, $locale: String!) {
          datoCmsProduct(slug: { eq: $slug }, locale: { eq: $locale }) {
              technicalSpec {
                  url
              }
              instruction {
                  url
              }
              declaration {
                  url
              }
              booklet {
                  url
          }
    }
```

I tried what you posted up @loganwishartcraig with my variable names, but it didn't work.

**Comment by loganwishartcraig** [comment]
Hey @adiusz 

You might want to check out the gatsby blog post outlining the method: [https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization/](https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization/)

I can't speak to your exact usecase, but in general you'd need to name the type the same as it is generated by whatever DatoCMS plugin you're using. You might want to ask on the [gatsby-source-datocms repo](https://github.com/datocms/gatsby-source-datocms) as they'd probably have more knowledge on how their plugin works!
